"""
Export Utilities
Handles PDF, Excel, and formatted exports
"""

import json
from datetime import datetime
import pandas as pd
from io import BytesIO


class ExportUtils:
    """Handles various export formats"""
    
    @staticmethod
    def create_excel_export(results: dict) -> BytesIO:
        """
        Create multi-sheet Excel workbook
        Sheet 1: Summary
        Sheet 2: Critical Errors
        Sheet 3: High Errors
        Sheet 4: All Errors
        """
        output = BytesIO()
        
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            # Sheet 1: Summary
            summary_data = {
                'Metric': [
                    'Total Logs',
                    'Suspicious Logs',
                    'Confirmed Errors',
                    'Critical Errors',
                    'High Priority Errors',
                    'Processing Time',
                    'Highest Severity',
                    'Requires Immediate Action'
                ],
                'Value': [
                    results.get('total_logs', 0),
                    len(results.get('suspicious_indices', [])),
                    len(results.get('error_events', [])),
                    len([e for e in results.get('error_events', []) if e.get('severity') == 'CRITICAL']),
                    len([e for e in results.get('error_events', []) if e.get('severity') == 'HIGH']),
                    f"{results.get('processing_time', 0):.2f}s",
                    results.get('highest_severity', 'UNKNOWN'),
                    'YES' if results.get('requires_immediate_attention') else 'NO'
                ]
            }
            df_summary = pd.DataFrame(summary_data)
            df_summary.to_excel(writer, sheet_name='Summary', index=False)
            
            # Sheet 2: Critical Errors
            critical_errors = [e for e in results.get('error_events', []) if e.get('severity') == 'CRITICAL']
            if critical_errors:
                df_critical = pd.DataFrame(critical_errors)
                df_critical.to_excel(writer, sheet_name='Critical Errors', index=False)
            
            # Sheet 3: High Errors
            high_errors = [e for e in results.get('error_events', []) if e.get('severity') == 'HIGH']
            if high_errors:
                df_high = pd.DataFrame(high_errors)
                df_high.to_excel(writer, sheet_name='High Priority', index=False)
            
            # Sheet 4: All Errors
            if results.get('error_events'):
                df_all = pd.DataFrame(results['error_events'])
                df_all.to_excel(writer, sheet_name='All Errors', index=False)
        
        output.seek(0)
        return output
    
    @staticmethod
    def create_jira_format(error: dict) -> str:
        """Format error for JIRA ticket creation"""
        template = f"""
h2. {error.get('exception_class', 'Error')} in {error.get('component', 'Unknown Component')}

*Severity:* {error.get('severity', 'UNKNOWN')}
*Confidence:* {error.get('confidence', 0)*100:.0f}%
*Category:* {error.get('category', 'GENERIC')}

h3. Error Message
{{code}}
{error.get('message', 'No message available')}
{{code}}

h3. Possible Root Causes
{chr(10).join(['* ' + cause for cause in error.get('possible_root_causes', ['Unknown'])])}

h3. Recommended Actions
{chr(10).join(['# ' + action for action in error.get('recommended_actions', ['Investigate further'])])}

h3. Technical Details
* Stack Depth: {error.get('stack_trace_depth', 'Unknown')} frames
* Needs Review: {'Yes' if error.get('needs_review') else 'No'}

---
_Generated by CRYSYS v3.0 on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_
"""
        return template.strip()
    
    @staticmethod
    def create_slack_format(error: dict) -> str:
        """Format error for Slack message"""
        severity_emoji = {
            'CRITICAL': '🔴',
            'HIGH': '🟠',
            'MEDIUM': '🟡',
            'LOW': '🟢',
            'INFO': '🔵'
        }
        
        emoji = severity_emoji.get(error.get('severity', 'INFO'), '⚪')
        
        message = f"""
{emoji} *{error.get('severity', 'UNKNOWN')} Error Detected*

*Type:* {error.get('exception_class', 'Unknown')}
*Component:* {error.get('component', 'Unknown')}
*Confidence:* {error.get('confidence', 0)*100:.0f}%

*Message:*
```
{error.get('message', 'No message')[:200]}
```

*Top Root Cause:* {error.get('possible_root_causes', ['Unknown'])[0] if error.get('possible_root_causes') else 'Unknown'}
*Recommended Fix:* {error.get('recommended_actions', ['Investigate'])[0] if error.get('recommended_actions') else 'Investigate'}
"""
        return message.strip()